[package]
name = "fuse"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "fuse"

[dependencies]
libc = { version = "0.2.*", optional = true }

[features]
default = ["std", "respond_async"]
respond_async = ["std"]
std = []

libc_fuse_mount = ["libc"]

nightly_syscall_fuse_mount = []

unstable_bmap = []
unstable_getlk = []
unstable_ioctl = []
unstable_setattr = []
unstable_setlk = []
