[package]
name = "fuse"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "fuse"

[features]
unstable_fuse_access = []
unstable_fuse_bmap = []
unstable_fuse_create = []
unstable_fuse_fallocate = []
unstable_fuse_flush = []
unstable_fuse_fsync = []
unstable_fuse_fsyncdir = []
unstable_fuse_getattr = []
unstable_fuse_getlk = []
unstable_fuse_getxattr = []
unstable_fuse_init_response_for_request = []
unstable_fuse_ioctl = []
unstable_fuse_link = []
unstable_fuse_listxattr = []
unstable_fuse_lookup = []
unstable_fuse_lseek = []
unstable_fuse_mkdir = []
unstable_fuse_mknod = []
unstable_fuse_readdir = []
unstable_fuse_readlink = []
unstable_fuse_release = []
unstable_fuse_releasedir = []
unstable_fuse_removexattr = []
unstable_fuse_rename = []
unstable_fuse_rmdir = []
unstable_fuse_setattr = []
unstable_fuse_setlk = []
unstable_fuse_setxattr = []
unstable_fuse_statfs = []
unstable_fuse_symlink = []
unstable_fuse_unlink = []
unstable_fuse_write = []
