[package]
name = "fuse"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "fuse"

[features]
default = ["std"]
std = []

unstable_cuse_flush = []
unstable_cuse_fsync = []
unstable_cuse_ioctl = []
unstable_fuse_access = []
unstable_fuse_bmap = []
unstable_fuse_create = []
unstable_fuse_fallocate = []
unstable_fuse_flush = []
unstable_fuse_fsync = []
unstable_fuse_fsyncdir = []
unstable_fuse_getlk = []
unstable_fuse_ioctl = []
unstable_fuse_lseek = []
unstable_fuse_removexattr = []
unstable_fuse_setattr = []
unstable_fuse_setlk = []
unstable_fuse_setxattr = []
unstable_fuse_statfs = []
