[package]
name = "fuse"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "fuse"

[features]
default = ["std"]
std = []

unstable_access = []
unstable_bmap = []
unstable_create = []
unstable_fallocate = []
unstable_flush = []
unstable_fsync = []
unstable_fsyncdir = []
unstable_getlk = []
unstable_ioctl = []
unstable_lseek = []
unstable_removexattr = []
unstable_setattr = []
unstable_setlk = []
unstable_setxattr = []
unstable_statfs = []
